version: '3.9'

services:
  liferay-dxp1:
    image: liferay/dxp:latest
    container_name: liferay-dxp1
    ports:
    - "8080:8080"

  liferay-dxp2:
    image: liferay/dxp:latest
    container_name: liferay-dxp2
    ports:
    - "8081:8080"


  web-server:
    build:
      context: .
    image: apache_image
    container_name: web_server
    ports:
      - "80:80"
    restart: always